### ISSUE TITLE
list rollup as a peerDependency instead of devDependency

### ISSUE THREAD

**Issue by chrstntdd** [darionco/rollup-plugin-web-worker-loader#13]
Hello there! 

I just spun up a project that uses [yarn 2/berry](https://github.com/yarnpkg/berry) and attempted to use your loader and encountered some troubles. Looks like your project has `rollup` in the `package.json` as a `devDependency` when it should be a `peerDependency` -  that we expect users of this plugin to have rollup installed themselves. [This is the error I was encountering.](https://yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-) It looks like most of the official plugins [do it this way](https://github.com/rollup/plugins/blob/371f4246068f3f469e046ecbe329b897eed9a692/packages/alias/package.json#L46)

This should be a straight forward change and I think it would be beneficial. Glad to make these changes if they're welcome.

**Comment by darionco** [comment]
Hi, good catch, thanks!

PRs are always welcome!

**Comment by darionco** [comment]
This feature will be released in version 1.0.0, thanks!
