### ISSUE TITLE
WorkerFactory assignment does not seem to be processed by TypeScript

### ISSUE THREAD

**Issue by stevehobbsdev** [darionco/rollup-plugin-web-worker-loader#15]
We've noticed when using this library that this line appears directly in our output file, even though we're transpiling to ES5 using TypeScript:

```
const WorkerFactory = createInlineWorkerFactory(/* rollup-plugin-web-worker-loader */function () {
```

Which means that we're unable to use this in IE11, which supports the WebWorker API. Digging through the code, I can see why this is happening as the worker module is [signalled as being a virtual module](https://github.com/darionco/rollup-plugin-web-worker-loader/blob/2c71425831cf3d259e03c7fb06a6de9fb089b29a/src/index.js#L114). It is then [filtered out](https://github.com/rollup/rollup-pluginutils/blob/master/src/createFilter.ts#L34) before TypeScript has a chance to process it.

I can understand why it's like that, though. Perhaps the answer is to [not use ES6 code here](https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/utils.js#L41) for maximum compatibility. Otherwise, we have no way of processing it.

Any other suggestions? Here is our rollup plugin config:

```js
const getPlugins = shouldMinify => {
  return [
    resolve({
      browser: true
    }),
    commonjs(),
    webWorkerLoader({
      sourceMap: !isProduction,
      preserveSource: !isProduction
      // pattern: /^[^\/].+\.worker\.ts$/
    }),
    typescript({
      clean: true,
      useTsconfigDeclarationDir: true,
      include: [
        'src/**/*.ts',
        'src/**/*.js',
        'node_modules/rollup-plugin-web-worker-loader/**/*'
      ],
      tsconfigOverride: {
        noEmit: false,
        sourceMap: true,
        compilerOptions: {
          lib: ['dom', 'es6']
        }
      }
    }),
    shouldMinify && terser(),
    sourcemaps()
  ];
};
```

`tsconfig.json` here:

```json
{
  "compilerOptions": {
    "lib": ["dom", "webworker"],
    "target": "es5",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": true,
    "declarationDir": "./dist/typings",
    "moduleResolution": "node",
    "allowJs": true
  },
  "exclude": ["./__tests__", "./dist/typings"]
}
```
These might be a little bit convoluted - in an attempt to get this to work (originally we couldn't even get our worker module to transpile properly, but that's fixed now).

**Comment by darionco** [comment]
oh soot, I'm sorry, I don't usually compile for IE11. At some point I had tested for it but I guess this is a regression/new bug.

I'll make the changes to not use >ES5 in code that won't be transpiled when I have a bit of time. Otherwise, if you can't wait, PRs are welcome!
