### ISSUE TITLE
Using WorkerLoaderHelper with SSR frameworks

### ISSUE THREAD

**Issue by adamjmcgrath** [darionco/rollup-plugin-web-worker-loader#17]
Hi, we're seeing the error `ReferenceError: Blob is not defined` when we try and use the output of `WorkerLoaderHelper.js` code in SSR environments like Gatsby and Next.js (eg https://github.com/zeit/next.js/issues/11967#issuecomment-616383108)

I've created a minimal test case here https://gist.github.com/adamjmcgrath/f697de44cf7b5056ac108edcc9815bff

Essentially, `module.require` is undefined in https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/WorkerLoaderHelper.js#L2

So `kRequire` is `null` https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/WorkerLoaderHelper.js#L64

And this branch of code https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/WorkerLoaderHelper.js#L73-L77 is run in node

Which throws: `ReferenceError: Blob is not defined`

I've noticed that reverting this https://github.com/darionco/rollup-plugin-web-worker-loader/commit/14809d30b17115b7089e91930d4010c25c95ee13 fixes the issue. But I'm not sure what the `module.require` logic was being used for, or why it's not working now

**Comment by darionco** [comment]
Hi, thanks for the awesome report!

I am a bit busy with work right now but based on your research I think there's a simple fix for this, changing [line 2 in `src/WorkerLoaderHelper.js`](https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/WorkerLoaderHelper.js#L2) from:
```
const kRequire = kIsNodeJS && typeof module.require === 'function' ? module.require : null; // eslint-disable-line
```
to
```
const kRequire = kIsNodeJS ? typeof module.require === 'function' && module.require || typeof require === 'function' && require : null; // eslint-disable-line
```

should solve your issue, if you have time to test this and submit a PR, I would appreciate it. Otherwise I'll test it as soon as I have a bit more time.

**Comment by adamjmcgrath** [comment]
Thanks for the suggestion! I'll try it out over the weekend and get back to you.

**Comment by darionco** [comment]
This issue's fix will be available in the next release, thanks!

**Comment by adamjmcgrath** [comment]
Awesome! Thanks @darionco!

**Comment by darionco** [comment]
I have released version 1.0.0 where the fix to this issue is included. Please note that the plugin now requires the configuration to explicitly state the target platform for the build when targeting NodeJS

**Comment by adamjmcgrath** [comment]
Hi @darionco 

For our use case, we want to offer a browser only SDK that doesn't blow up when you import it into Gatsby/Next etc. So we don't really want to specify the `targetPlatform`, we'd rather that was evaluated at 'run time' (ie. build time of the consuming app) 

Would you consider releasing 79b9d80 as `0.2.1` which we can use while we figure out available options?

**Comment by darionco** [comment]
Hi @adamjmcgrath, I got a couple other e-mails asking for the return of this feature so I added "auto" to the `targetPlatform` list and made it the default target in release `1.1.0`. Hopefully this change helps.

**Comment by adamjmcgrath** [comment]
@darionco yep - that does the trick. thank you! 🙏
