### ISSUE TITLE
Webpack error: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by adamjmcgrath** [darionco/rollup-plugin-web-worker-loader#19]
Hi, we're hitting an issue when webpack builds the output in CI mode https://github.com/auth0/auth0-spa-js/issues/447

When we tested it originally we noticed a warning: `require function is used in a way in which dependencies cannot be statically extracted` but thought we could ignore it.

But with the CI environment enabled, this turns into an error.

It seems webpack doesn't like the `var kRequire = require; kRequire('something');` happening in https://github.com/darionco/rollup-plugin-web-worker-loader/blob/master/src/helper/node/WorkerClass.js#L4

**Comment by darionco** [comment]
Webpack is a pain to work with lol, they provide a way to not process certain `require` statements but they throw a warning when you use it... that warning becomes an error in CI because they upgrade warnings to errors.

Let me see what can be donee here.

**Comment by darionco** [comment]
Fixed in 1.1.2

**Comment by adamjmcgrath** [comment]
Thanks for resolving that so quickly, although I think you may have published a local branch
I'm seeing a file called `plugin/options.js` for example in the installed package

**Comment by adamjmcgrath** [comment]
Also, we're seeing a different warning `Can't resolve 'worker_threads' in '/dist'`
(although - it's not failing with `CI=true` which is good)

**Comment by darionco** [comment]
ohh ffs, you are right, I am refactoring other parts of the code and that file lingered there for some reason.... I'll just release the refactored version soon.

The new warning is not showing up on my test project, could you elaborate on the repro steps?

**Comment by adamjmcgrath** [comment]
>  I'll just release the refactored version soon.

Cool, np

> The new warning is not showing up on my test project, could you elaborate on the repro steps?

I'll setup a minimal case and share it with you some time over the weekend

Thanks!

**Comment by adamjmcgrath** [comment]
> I'll setup a minimal case and share it with you some time over the weekend

Have raised #20
