### ISSUE TITLE
how can i pack the worker without sourcemap。

### ISSUE THREAD

**Issue by xudamin** [darionco/rollup-plugin-web-worker-loader#27]
i find whatever i set the sourcemap and inline param，output file always pack with the sourcemap code。
how could i pack without them。

**Comment by darionco** [comment]
I just tested with this configuration and the source map was not included:
```
    plugins: [
        webWorkerLoader({
            inline: true,
            sourcemap: false,
        }),
    ],
```

Maybe I am misunderstanding your issue, could you explain a bit more?

**Comment by xudamin** [comment]
sorry! i seem to find the way。
i set my development environment 。
`
 {
    sourcemap: 'inline',
    inline: false,
 }
`
my prod environment
`
  {
      sourcemap: false,
      inline: true
  }
`
and when i pack the project. i run them all. cause that my ouput folder contain xx.js xx.min.js web-worker-0.js.
i was wrong to think that web-worker-0.js ls pack from prod environment,  i just found that x.min.js contain the worker code。
my fault! ^_^
