### ISSUE TITLE
import error when run in rollup -c.

### ISSUE THREAD

**Issue by xudamin** [darionco/rollup-plugin-web-worker-loader#29]
i run with the server with ` cross-env NODE_ENV=Develop rollup -c build/rollup.config.js -w`
when i change my component code where i import the webworker and save.
there appear an error `Error: 'default' is not exported by src\worker\PlaneLineMergeWorker.js`
but when i restart the server.that error disappear.

![11](https://user-images.githubusercontent.com/17488002/89850608-491a8c80-dbbd-11ea-87b2-03c3da004391.png)

**Comment by darionco** [comment]
This is an issue with how rollup watches files, I had a similar issue in the past but I thought it was fixed, maybe something changed within rollup?

What version of rollup are you using? I'll give this a try tomorrow.

Thank for the report.

**Comment by xudamin** [comment]
i use rollup v1.21.4

**Comment by xudamin** [comment]
I'll try to update rollup to latest

**Comment by darionco** [comment]
I've been testing this for a while and was unable to reproduce.

If you think this is still an issue feel free to reopen this bug with further repro steps or a small project that reproduces the issue.

**Comment by xudamin** [comment]
I seem to have found the cause of the problem。  when i import the worker in more than one place。This problem will arise。
