### ISSUE TITLE
Rollup format ESM not working any more

### ISSUE THREAD

**Issue by TheoRettisch** [darionco/rollup-plugin-web-worker-loader#32]
Since V1.4.0 my worker is not functioning any more when using ESM as format in Rollup. 

Seems the change to format IIFE in load.js is causing the problem:
`bundle.generate({format: 'iife', name: 'worker_code', sourcemap: true})`

Could you maybe make this dynamic based on the format used by Rollup?

**Comment by darionco** [comment]
I haven’t been able to reproduce your issue.

Could you send me an example of your config? Or even better a small project to reproduce the issue?

The internal module config shouldn’t be an issue but I might have overlooked a use case.

Thank you!

**Comment by TheoRettisch** [comment]
I tried to reproduce the issue on a smaller scale but was also unable to. Sorry for wasting your time here, should have done it in the first place.

Anyways thanks for looking into it and the awesome plugin!

**Comment by darionco** [comment]
No worries. Feel free to reopen this issue if you continue to encounter problems with the plugin.
