### ISSUE TITLE
Does not work with esm.

### ISSUE THREAD

**Issue by TheComputerM** [darionco/rollup-plugin-web-worker-loader#34]
It is showing that UMD and IIFE are not supported for code splitting, I have `inline` set as false.

**Comment by darionco** [comment]
Could you let me know why you closed this issue? I was going to take a look later today.

**Comment by TheComputerM** [comment]
Sorry, I don't know much about rollup plugins so I am not sure what caused the error. The error appears when I try to use this plugin with [sapper](https://github.com/sveltejs/sapper-template-rollup). I am sorry that I could not provide any details (as I am dumb), I closed this because I found a workaround.

**Comment by darionco** [comment]
Nah man, you’re not dumb, the fact that you took the time to report a bug shows just that.

I’ll take a look and update this issue, thanks!

**Comment by darionco** [comment]
Ok, after trying to reproduce this error for a while I haven't been to reproduce it, closing.
