### ISSUE TITLE
Support for return just the base64 encode

### ISSUE THREAD

**Issue by tinchoz49** [darionco/rollup-plugin-web-worker-loader#36]
Hey @darionco, how are you?

I'm working in a project where I have to load an AudioWorkletProcessor and is basically the same thing as a Worker but it has a different way to instantiate it.

I like your plugin because is doing what I need, creating a inline version of a worker file in base64 but I want to know if it could be possible to add an option to just return the base64 string instead of the worker so I can do the job of `createBase64WorkerFactory` by myself

**Comment by darionco** [comment]
Sorry for the late reply, I see you've closed the issue, I am sorry I didn't get to you fast enough. I'll look at this again in the future anyway. Reopening.

**Comment by tinchoz49** [comment]
Hey @darionco, I start thinking that maybe it shouldn't be a feature of this plugin, that's why I close it. But if you think it could,  that's great :+1:

**Comment by darionco** [comment]
Makes sense to me because, although other plugins already offer the functionality to load a file as base64, this one packs an entire module and all its dependencies.

**Comment by tinchoz49** [comment]
> this one packs an entire module and all its dependencies.

that's right!

**Comment by darionco** [comment]
Sorry for the long wait. I have added `base64` as a `targetPlatform` in the options. This setting will always force the result to be inlined and the `import` statement will return a string with the worker source encoded in base64.

NOTE: The string does not include a mime type.

Released in 1.6.0
