### ISSUE TITLE
import error when run rollup -c -w

### ISSUE THREAD

**Issue by xudamin** [darionco/rollup-plugin-web-worker-loader#37]
when i import the worker in more than one place, there will appear an error Error: 'default' is not exported by src\worker\xxxWorker.js。
if there is only one file import the worker, there is nothing wrong.

**Comment by darionco** [comment]
I have tried to reproduce this bug in several ways and importing the worker from different files while in watch mode seems to work just fine. Do you have a repo or example project I can look at? Thanks!

**Comment by darionco** [comment]
Closing as I am not able to reproduce this issue. Feel free to re-open with more details.
