### ISSUE TITLE
error when build inline worker

### ISSUE THREAD

**Issue by LoveofRedMoon** [darionco/rollup-plugin-web-worker-loader#39]
see https://github.com/LoveofRedMoon/bug-vite-worker-20201125.git
vite app use worker with the following config 
```js
plugins: [
..........,
require('rollup-plugin-web-worker-loader')({
        targetPlatform: 'browser',
        pattern: /(.+)\?worker$/,
        extensions: resolver_1.supportedExts,
        sourcemap: false // it's inlined so it bloats the bundle
    })
]
```

when build some workers with dynamicImports, the rollup will erroring: 
`UMD and IIFE output formats are not supported for code-splitting builds.`

I'm not sure if there is a better way to resolve this problem, 
one way to resolve is modify `load.js`
to 
```js
bundle.generate({format: 'iife', name: 'worker_code', sourcemap: true, inlineDynamicImports: true}).then(result => {
                    resolve(handleBundleGenerated(state, config, addWatchFile, id, workerID, result));
                }).catch(reject);
```
use `inlineDynamicImports`

**Comment by darionco** [comment]
Really good catch and the solution works great!

In the future I am planning to release version 2.0 which will not run a new instance of rollup, for now though, your solution is perfect. Thank you!

Fix released in version 1.4.1
