### ISSUE TITLE
Pattern option doesn't affect on chunk's name

### ISSUE THREAD

**Issue by crutch12** [darionco/rollup-plugin-web-worker-loader#41]
From README:
```
pattern?: RegEx,  // A RegEx instance describing the pattern that matches the files to import as
                            // web workers. If capturing groups are present, the plugin uses the contents of the
                            // last capturing group as the path to the worker script. Default: /web-worker:(.+)/
```

Sounds like if you have worker with name `my-worker.js` and import it with `web-worker:./my-worker.js` you will get chunk file with name `my-worker.js`

But I checked the source code:
https://github.com/darionco/rollup-plugin-web-worker-loader/blob/3868786fe35a52de33ab90b142233743b97a018e/src/plugin/resolveId.js#L48

And it doesn't work like this, it always generates file with `web-worker-0.js` name

Is this a bug? I would like to set worker's name

**Comment by darionco** [comment]
The problem with this is file name duplication, the current solution is to use generated file names, although I can see why you would want to keep deterministic file names. I have added a configuration option `preserveFileNames` that when set to `true` keeps the input file names as output as best as possible. If a duplicated file name is encountered, it appends `-n`, making the file names non deterministic. If carefully used should help you achieve your goal though.

Released in 1.6.0
