### ISSUE TITLE
create worker by URL.createObjectURL()

### ISSUE THREAD

**Issue by shiyafei** [darionco/rollup-plugin-web-worker-loader#42]
Refer to the ts code example to create webworker() by URL.createObjectURL()

`import { MessageManager } from './MessageManager'
import WebWorker from 'web-worker:./Worker.ts'

function main(): void {
  const messageManager = new MessageManager('This instance was created on the main thread')

  const workerBlob = new Blob([`console.log(123)`], {
    type: 'application/javascript',
  })
  const worker = new WebWorker(URL.createObjectURL(workerBlob))
  worker.postMessage({ type: 'init', args: 'This instance was created in a worker' })

  messageManager.sayHello('main thread')
  worker.postMessage({ type: 'exec', func: 'sayHello', args: 'web worker' })

  messageManager.printMessage()
  worker.postMessage({ type: 'exec', func: 'printMessage', args: null })
}

window.addEventListener('DOMContentLoaded', () => {
  main()
})
`

but report an error:
`Uncaught TypeError: Failed to construct 'Worker': parameter 2 ('options') is not an object.
    at new WorkerFactory (sdk.js:67)
    at main (sdk.js:99)
    at sdk.js:107`

**Comment by darionco** [comment]
it's supposed to be:
```
import WebWorker from 'web-worker:./Worker.ts'
const worker = new WebWorker()
```
