### ISSUE TITLE
Terser / minified worker code?

### ISSUE THREAD

**Issue by dbartle** [darionco/rollup-plugin-web-worker-loader#44]
Sorry if I'm missing something obvious, this is my first attempt at using rollup.

I'm using your plugin successfully to inline my worker. The worker includes a significant amount of code and is about 1.5mb (it includes an entire Emscripten project). This has been incredibly useful because shipping a library with several files and importing workers and wasm puts a lot of burden on the end user to figure a lot of things out even to do "hello world".

When I rollup the project I see the resulting output is 2.2mb, and minified (terser) output is the same size. I realized that what's happening is the worker has about ~500kb of extra un-minified source, which then gets base64 encoded and inlined before terser is invoked. So the final minification step on the does not do anything useful since the majority of the JS has been encoded.

Is there a way to include minification in the worker before it gets base64 encoded? Inline is definitely the end result I want, but ideally in as compact a form as possible.

**Comment by darionco** [comment]
This is an interesting problem, could you paste your rollup config? I feel like this should work but I might be wrong

**Comment by dbartle** [comment]
For sure. This may look somewhat familiar since I started with your template.

```javascript
'use strict';
const path = require('path');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const typescript = require('rollup-plugin-typescript2');
const workerLoader = require('rollup-plugin-web-worker-loader');
const pkg = require('./package.json');
const { babel } = require('@rollup/plugin-babel');
const terser = require('rollup-plugin-terser').terser;
const { DEFAULT_EXTENSIONS } = require('@babel/core');

const extensions = [...DEFAULT_EXTENSIONS, '.ts'];

console.log(process.env.TARGET);
console.log(extensions);

function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

const iifeBundleName = pkg.name
  .split('-')
  .map(word => capitalizeFirstLetter(word))
  .join('');
console.log(iifeBundleName);

export default {
  input: [path.resolve(__dirname, pkg.entry)],
  output: [
    {
      file: path.resolve(__dirname, pkg['module']),
      format: 'esm',
      sourcemap: false,
    },
    {
      file: path.resolve(__dirname, 'dist', 'esm', 'index.min.js'),
      format: 'esm',
      sourcemap: false,
      plugins: [terser()],
    },
    {
      file: path.resolve(__dirname, pkg.iife),
      format: 'iife',
      name: iifeBundleName,
      sourcemap: false,
    },
    {
      file: path.resolve(__dirname, 'dist', 'iife', 'index.min.js'),
      format: 'iife',
      name: iifeBundleName,
      sourcemap: false,
      plugins: [terser()],
    },
  ],
  plugins: [
    nodeResolve({ extensions }),
    commonjs(),
    workerLoader({
      targetPlatform: 'browser',
      sourcemap: false,
    }),
    typescript({
      typescript: require('typescript'),
      cacheRoot: path.resolve(__dirname, '.rts2_cache'),
      clean: true,
    }),
    babel({
      extensions: extensions,
      babelHelpers: 'runtime',
      exclude: '**/node_modules/**',
      compact: true
    }),
  ],
};
```

This is from this pull request, for context: https://github.com/Picovoice/porcupine/pull/361

**Comment by jeetiss** [comment]
I faced with this problem too, @darionco maybe `rollup-plugin-web-worker-loader` should minify worker code on default?

libraries are shipped without minification and this is not clear that I need minification plugin that will work before converting code to worker blob

and as I understand `rollup-plugin-terser` can not minificate only worker code

**Comment by darionco** [comment]
Interesting, I understand the issue.

The plugin inherits the plugins added to the global config object and uses them to process the files passed to it, it uses the `skipPlugins` option to avoid using problematic plugins but it doesn't have a way to add extra plugins to the process.

In your config, you are adding terser on a per-file basis, which makes sense but makes it so the plugin doesn't know that it should be minifying the code.

I'd avoid minifying the code by default just because different minifiers will produce different outputs and it should be up to the users to decide how they want the plugin to handle their code.

I think the real solution here is to allow for an option to pass an array of extra plugins to the worker loader plugin, that way users have full control over their output.

thoughts?

**Comment by dbartle** [comment]
> I think the real solution here is to allow for an option to pass an array of extra plugins to the worker loader plugin, that way users have full control over their output.

That makes the most sense to me, and could potentially handle some other cases. It seems that the worker plugin is a fully-fledged rollup "sub-project" so ultimately having that control over rollup is in alignment.

**Comment by darionco** [comment]
released in version 1.6.1

**Comment by dbartle** [comment]
Thank you!

**Comment by kdziamura** [comment]
Encountered the same problem - need to run a couple of additional plugins on top of a worker bundle.

@darionco couldn't find this feature in the docs and in the codebase. Also, `master` has `1.6.0` in the `package.json` but `1.6.1` is published to `npm` 🤔
