### ISSUE TITLE
rollup-plugin-babel does not transpile helper functions

### ISSUE THREAD

**Issue by darionco** [darionco/rollup-plugin-web-worker-loader#6]
as reported in #1 by @PixlRainbow

I have just tried pairing this plugin with rollup-plugin-babel and found that for some reason, the web worker runs after babel and doesn't get its helper functions (e.g. createBase64WorkerFactory) transpiled to ES5 even though I ordered the babel plugin after your plugin.

**Comment by PixlRainbow** [comment]
[babelroll.zip](https://github.com/darionco/rollup-plugin-web-worker-loader/files/3847005/babel-roll.zip)  
Here is the demo you requested. It generates a PDF file in a web worker, and passes it back to the main thread which opens it in a new tab.

**Comment by PixlRainbow** [comment]
I have changed the helper functions by hand to make them compatible with ES5 and it appears the worker blob itself does not get transpiled either

**Comment by darionco** [comment]
turns out your project is misconfigured, you need to explicitly tell babel you want to transpile the source to ES5 otherwise it just doesn't, if in the example project you add the `presets` variable to your babel plugin it transpiles the helper functions properly:
```
    plugins: [
        webWorkerLoader(),
        resolve(),
        jscc({
            values: {_PRODUCTION: 1},
            exclude: 'node_modules/**'
        }),
        babel({
            exclude: 'node_modules/**',
            presets: [
                [
                    '@babel/env',
                    {
                        targets: { ie: '11' },
                        useBuiltIns: 'entry',
                        corejs: { version: 3, proposals: true },
                    },
                ],
            ],

        })
    ]
```
as for the worker code itself, you are importing a bunch of ES6 libraries from your `node_modules`:
```
import 'pdfkit/js/pdfkit.standalone';
import 'svg-to-pdfkit';
import 'blob-stream-browserify';
```
and in the configuration, you are explicitly telling babel to exclude all the sources from `node_modules`:
```
        babel({
            exclude: 'node_modules/**',
            ...
```
if you comment out that line and include the `presets` as suggested above, everything works as you would expect it to:
```
        babel({
            // exclude: 'node_modules/**',
            presets: [
                [
                    '@babel/env',
                    {
                        targets: { ie: '11' },
                        useBuiltIns: 'entry',
                        corejs: { version: 3, proposals: true },
                    },
                ],
            ],

        })
```

That being said, looking through the plugin's code revealed a few bugs that will be fixed in the next release, thanks!
