### ISSUE TITLE
Typescript ?

### ISSUE THREAD

**Issue by tsavo-vdb-knott** [darionco/rollup-plugin-web-worker-loader#8]
Can this plugin be used with Typescript ? I really could use some help - Migrating from Webpack to Rollup and currently am considering going back to webpack bc the experience with workers on Rollup is so bad. If you could post an example project of how you are using this plugin and the associated folder structure, that would be incredibly helpful.

**Comment by darionco** [comment]
Hi, I am putting together a small project for you to look at, it's going to take me a little bit. I'll post back when it's ready.

**Comment by darionco** [comment]
Please look at my example project here:
https://github.com/darionco/rollup-typescript-webworkers

It uses a few of typescript features to demonstrate compatibility. Hope it helps.
