### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by benmccann** [darionco/rollup-plugin-web-worker-loader#9]
A contributor to our project put together a PR (https://github.com/chartjs/Chart.js/pull/7029) proposing to use this plugin, but it's failing and we're stuck on figuring out why. 

I was wondering if you might have any ideas what's going wrong based on the error message or if you spot anything obviously wrong in our code

>Error: Could not load rollup-plugin-worker-loader::module:../BasicChartWebWorker (imported by test/specs/platform.basic.tests.js): Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at tryParse (node_modules/rollup/dist/shared/node-entry.js:9713:23)
    at Module.setSource (node_modules/rollup/dist/shared/node-entry.js:10076:33)
    at node_modules/rollup/dist/shared/node-entry.js:12362:20
    at async Promise.all (index 11)
    at async Promise.all (index 0)

Here's the file with the `import`: https://github.com/benmccann/Chart.js/blob/PR7029/test/specs/platform.basic.tests.js
Here's the rollup config: https://github.com/benmccann/Chart.js/blob/PR7029/karma.conf.js

Thank you so much for the plugin and any help you can provide!

**Comment by darionco** [comment]
ok, checked out your rebased version and found the issue.

The file `BasicChartWebWorker.js` is importing the library from source:
```
import Chart from '../src';
```

Which means everything needs to be rebuilt, looking at your `rollup.config.js` file I noticed that you are indeed importing JSON files and handling them with the json loader plugin:
```
const json = require('@rollup/plugin-json');
...
plugins: [
    json(),
     ...
```

So you can either import the pre-built library or add the `@rollup/plugin-json` plugin to your `karma.conf.js` file.

I tested the latter option and the tests passed without issues.

Hopefully this fixes your issues!

**Comment by benmccann** [comment]
Wow, thank you so much for taking a look! I will try out your suggestion
